  prometheusSpec:
    retention: 3d
    resources:
      requests: {cpu: 100m, memory: 256Mi}
      limits: {cpu: 300m, memory: 512Mi}
    storageSpec:
      volumeClaimTemplate:
        spec:
          resources:
            requests: {storage: 5Gi}
grafana:
  persistence:
    enabled: true
    size: 2Gi
  resources:
    requests: {cpu: 50m, memory: 128Mi}
    limits: {cpu: 200m, memory: 256Mi}
alertmanager:
  alertmanagerSpec:
    resources:
      requests: {cpu: 25m, memory: 64Mi}
      limits: {cpu: 100m, memory: 128Mi}